#!/usr/bin/python

import cPickle

# generated by analysis/sf_streets.py
records_cross = cPickle.load(file('/tmp/sf-crossstreets.pickle'))
f = file('/tmp/photo_ids.crossstreets.txt', 'w')
for r in records_cross:
  cross = r[2]
  addy = [x for x in cross if x.startswith("address:")]
  block = [x for x in cross if x.startswith("block:")]
  tiny = (len(cross) == 1 and cross[0].startswith("tiny:"))
  if addy or block or tiny:
    f.write(r[0] + '\n')
  elif len(cross) > 1:
    f.write(r[0] + '\n')
f.close()

#file('/tmp/photo_ids.crossstreets.txt', 'w').write('\n'.join(
#    [r[0] for r in records_cross]) + '\n')

# generated by analysis/sf_residences.py
records_residences = cPickle.load(file('/tmp/sf-residences.pickle'))
file('/tmp/photo_ids.residences.txt', 'w').write('\n'.join(
    [r[0] for r in records_residences]) + '\n')

# generated by analysis/sf_freestanding_streets.py
records_free = cPickle.load(file('/tmp/sf-freestanding.pickle'))
file('/tmp/photo_ids.free.txt', 'w').write('\n'.join(
    [r[0] for r in records_free]) + '\n')
