application: oldbostonphotos

version: 2014-04-02
runtime: python27
threadsafe: true

api_version: 1

handlers:
- url: /jquery
  static_dir: static/jquery
- url: /dots
  static_dir: static/dots
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /
  script: app.app
- url: /about
  static_files: static/about.html
  upload: static/about.html
- url: /feedback
  static_files: static/feedback.html
  upload: static/feedback.html
- url: /upload
  script: app.app
- url: /thumb/.*
  script: app.app
  
- url: /records.js.zip
  static_files: static/records.js.zip
  upload: static/records.js.zip
- url: /(.*\.js)
  static_files: static/js/\1
  upload: static/js/.*\.js
- url: /(.*\.css)
  static_files: static/styles/\1
  upload: static/styles/.*\.css
- url: /(.*\.(gif|png|jpg))
  static_files: static/imageresources/\1
  upload: static/imageresources/.*\.(gif|png|jpg)
  
- url: .*
  script: app.app

# TODO(danvk): restore this before launching
# - url: /
#   static_files: viewer.html
#   upload: viewer.html

builtins:
- remote_api: on
#- datastore_admin: on
