name: e2etest

on: [push]

jobs:
  geocoder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Expand geocache
      run: |
        tar -xzf geocache.tgz
    - name: Run geocoder
      run: |
        poetry run ./generate-geocodes.py --ids_filter test/random200-ids.txt --images_ndjson data/images.ndjson --output_format id-location.txt --geocode > test/random200-geocoded.txt 2> test/random200.logs.txt
    - name: Check for diffs
      run: |
        git diff --exit-code test/

  cropper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Run cropper
      run: |
        poetry run ocr/crop_morphology.py --beta 2 --overwrite test/721675b.jpg
        poetry run ocr/crop_morphology.py --beta 2 --border_only --output_pattern '%s.border.jpg' test/721675b.jpg
    - name: Run photo detector
      run: |
        poetry run nyc/find_pictures.py test/*f.jpg > test/detected-photos.ndjson
    - name: Check for diffs
      run: |
        git diff --exit-code test/

  generation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Clone web site
      run: |
        cd ..
        git clone https://github.com/oldnyc/oldnyc.github.io.git
    - name: Run ingestion
      run: |
        PYTHONPATH=. poetry run data/ingest.py
    - name: Check for diffs
      run: |
        git diff --exit-code data/
    - name: Generate static site
      run: |
        export PYTHONPATH=.
        poetry run ./nyc/crops-to-json.py nyc/crops.txt > /tmp/crops.json
        poetry run ./nyc/records_to_photos.py data/images.ndjson /tmp/crops.json data/photos.ndjson
        echo '{"fixes": {}}' > ocr/feedback/fixes.json
        poetry run ./generate_static_site.py --leave-timestamps-unchanged
    - name: Check for diffs
      run: |
        cd ../oldnyc.github.io
        git diff --exit-code
