name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Run tests
      run: |
        poetry run pytest
    - name: Run ruff
      run: |
        poetry run ruff check
    - name: Save cache
      uses: actions/cache/save@v3
      with:
        path: ./.venv
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
