name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Run tests
      run: |
        poetry run pytest
    - name: Ruff lint
      run: |
        poetry run ruff check
    - name: Ruff format
      run: |
        poetry run ruff format --check
